---
title: Title Here
date: 2020-08-24
---

title: Awesome Title
author: Rowan
email: rowan@schaeferdesignco.com
description: > # this means to ignore newlines until "baseurl:"
  This is the website description.

# social links
twitter_username: rowan__s # DO NOT include the @ character, or else the build will fail!
github_username:  rowanschaefer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
